### PR TITLE
Add double quotations for labels for savedot

### PR DESCRIPTION
**Pull request by Paalon**
Solve #61.

### CODE REVIEW

**Comment by gdalle** [comment]
Thanks! Could you add a test while you're at it, to make sure that this doesn't happen again if the codebase changes?

**Comment by Paalon** [comment]
Test fails at code formatting, what should I do?

**Comment by gdalle** [comment]
> Test fails at code formatting, what should I do?

In the project environment, run

```julia
using JuliaFormatter, MetaGraphsNext
format(MetaGraphsNext)
```

JuliaFormatter is a good package to have in your base environment

**Comment by gdalle** [comment]
This is a breaking change so I'm bumping the version number, it will feature in the next minor release but that may not be right now

**Pull request merged**
