### PR TITLE
Update JLD2 compat

### PR DESCRIPTION
**Pull request by filchristou**

### CODE REVIEW

**Comment by gdalle** [comment]
Any idea why docs fail?

**Comment by ReubenJ** [comment]
There shouldn't be a `docs/Manifest.toml`, AFAIK. See `Graphs.jl`: https://github.com/JuliaGraphs/Graphs.jl/tree/master/docs. Removing the file (+ adding to .gitignore) should fix the issue.

It looks like the current manifest is out of sync with the docs `Project.toml` or something, causing the action to fail.

**Comment by ReubenJ** [comment]
Working in my own fork: https://github.com/ReubenJ/MetaGraphsNext.jl/pull/1

I can open a new PR or push the changes to your fork @filchristou.

**Comment by gdalle** [comment]
Either one would be great, thanks!

**Comment by ReubenJ** [comment]
Sounds good. Just opened #84 👍

**Pull request merged**
