### PR TITLE
Update JLD2 compat

### PR DESCRIPTION
**Pull request by ReubenJ**
Fixes #83

- Updates the JLD2 compat entry
  - Bump `MetaGraphsNext` patch version number
- Removes the unnecessary `docs/Manifest.toml`
- Remove outdated `strict` argument to `makedocs(...)`

### CODE REVIEW

**Comment by gdalle** [comment]
Sorry I also had to do those for #85 to pass CI, in retrospect I should have merged them in the other order. Can you merge `master` into this PR?

**Comment by gdalle** [comment]
Or we can merge it into the other one

**Comment by ReubenJ** [comment]
Oops... just got thoroughly confused switching between the branches and deleted the wrong one. I guess it's all sorted now?

**Comment by gdalle** [comment]
yup, all good! thanks

**Pull request closed without merging**
