### PR TITLE
Type-stable constructors

### LINKED ISSUE #6: Add constructors that infer the metadata types from the data values provided to constructor
The current `MetaGraph` constructor requires the user to explicitly specify the types of the metadata via the arguments `Label`, `VertexMeta`, and `EdgeMeta`. That seems a little unusual to me. It's much more common for constructors to determine the values of type parameters based on the data passed to the constructor, e.g.

```julia
julia> [1, 2]
2-element Array{Int64,1}:
 1
 2

julia> ["hello", "world"]
2-element Array{String,1}:
 "hello"
 "world"
```

It would be nice if there were some constructors like the following that infer the type parameters from the data:

```julia
MetaGraph(
    SimpleGraph(),
    vertices = [(:a, :color => "blue"), (:b, :color => "red")],
    edges = [(:a, :b, :linewidth => 2)]
)
```

The fallback for creating a typed but empty graph would be something like the following:

```julia
MetaGraph{SimpleGraph{Int}, Symbol, Dict{Symbol, String}, Dict{Symbol, Int}}()
```

which corresponds to how one normally creates a typed but empty object. E.g., for a typed but empty dictionary, you would use this:

```julia
Dict{Symbol, String}()
```

Or for a typed but empty vector:

```julia
Vector{Int}()
```

...although for arrays we have the sugar `Int[]`.

### LINKED ISSUE #27: Make keyword argument names consistent
For consistency, I propose changing this constructor signature from:
```julia
MetaGraphsNext.MetaGraph(graph::AbstractGraph{T}; Label, VertexData, EdgeData, graph_data, weight_function, default_weight) where T 
```
to
```julia
MetaGraphsNext.MetaGraph(graph::AbstractGraph{T}; label, vertex_data, edge_data, graph_data, weight_function, default_weight) where T 
```

### LINKED ISSUE #30: Type stability tests
The promise of this package is that it is type-stable. However, there are no tests that check this. I think that this type of test is of upmost importance for this package.

### PR DESCRIPTION
**Pull request by gdalle**
- Fix #6 by adding type-stable constructors
- Fix #27 by renaming keyword type arguments
- Fix #30 by adding inference tests
- Switch order of `MetaGraph` type parameters
- Remove `Symbol` as default vertex data type
- Tweak directedness traits to make `arrange` apply only to `MetaGraphs`
- Adapt `copy` to new constructors
- Implement full `==` comparing all fields
- Fix misleading documentation on weights
- Add `labels` function to iterate on vertex labels
- Stricter doc builds that error when something goes wrong are now part of CI for PRs

### CODE REVIEW

**Comment by gdalle** [comment]
Sorry @bramtayl this is a hell of a PR to review but we're making progress!

**Comment by bramtayl** [comment]
Thanks!

- I'm not sure "type unstable" in the right terminology here. Maybe something like "the type of the result depends on the keyword arguments, so if you are going to construct multiple graphs, do it inside a function, so the keyword arguments can constant propagate".
-  I'm not sure we need to export the positional constructor, although it's useful to have around. I like the `vertices_description` etc constructor though.
- Instead of `@asserts`, maybe we could throw more helpful errors? Why don't we set it up as a bounds check. After we check bounds, we can `@inbounds` everything. Then users can skip the bounds check if they want to play dangerous?
- As far as documenting the type stability, instead of just throwing in a bunch of `@inferred`, why don't we just have one or two examples comparing `MetaGraphs` with `MetaGraphsNext`? Everything else looks good!

**Comment by gdalle** [comment]
> * I'm not sure "type unstable" in the right terminology here. Maybe something like "the type of the result depends on the keyword arguments, so if you are going to construct multiple graphs, do it inside a function, so the keyword arguments can constant propagate".

Thanks, clarified this in the last commit

**Comment by gdalle** [comment]
> * I'm not sure we need to export the positional constructor, although it's useful to have around. I like the `vertices_description` etc constructor though.

As long as the positional constructor exists, it will be exported because it shares the name of the struct. It's not really a problem though cause it doesn't cause ambiguities

**Comment by gdalle** [comment]
> * As far as documenting the type stability, instead of just throwing in a bunch of `@inferred`, why don't we just have one or two examples comparing `MetaGraphs` with `MetaGraphsNext`? Everything else looks good!

There is a slight subtlety about tihs: the `@inferred` tests do not show up in the docs, they are only used for testing. Since I'm building the Markdown pages from pure Julia files with [Literate.jl](https://github.com/fredrikekre/Literate.jl), I can choose to filter out certain lines from the Markdown output. This is what the `#src` at the end of these lines is for.

If you want you can `git checkout` the PR and then build the docs locally to get an idea of the new look.

**Comment by gdalle** [comment]
> * Instead of `@asserts`, maybe we could throw more helpful errors? Why don't we set it up as a bounds check. After we check bounds, we can `@inbounds` everything. Then users can skip the bounds check if they want to play dangerous?

In the latest commit I turned `AssertionError`s into `ArgumentError`s with a more helpful message. I'm not necessarily in favor of `@inbounds` everywhere, at least not without careful profiling. For instance my gut tells me we lose way more time in `Dict` access than in bounds checking anyway. I would leave it as is for now

**Comment by gdalle** [comment]
@bramtayl ready for round 2 and possible approval

**Comment by bramtayl** [comment]
This looks great to me thanks!

**Review by bramtayl — APPROVED** [review]

**Pull request merged**
